/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./hooks/**/*.{js,ts,jsx,tsx}",
    "./context/**/*.{js,ts,jsx,tsx}"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#8B5CF6',
        income: '#4ADE80',
        expense: '#F87171',
        'teal': '#2DD4BF',
        'lilac': '#A78BFA',
        'category-groceries': '#A3E635',
        'category-utilities': '#60A5FA',
        'category-medicine': '#C084FC',
        'category-transport': '#F97316',
        'category-entertainment': '#F472B6',
        'category-savings': '#2DD4BF',
        'card-accent-blue-bg': '#EBF5FF',
        'card-accent-blue-text': '#2563EB',
        'dark-card-accent-blue-bg': '#172554',
        'dark-card-accent-blue-text': '#93C5FD',
        'card-accent-green-bg': '#F0FDF4',
        'card-accent-green-text': '#16A34A',
        'dark-card-accent-green-bg': '#14532D',
        'dark-card-accent-green-text': '#A7F3D0',
        'card-accent-purple-bg': '#FAF5FF',
        'card-accent-purple-text': '#9333EA',
        'dark-card-accent-purple-bg': '#3B0764',
        'dark-card-accent-purple-text': '#E9D5FF',
        'card-accent-orange-bg': '#FFF7ED',
        'card-accent-orange-text': '#EA580C',
        'dark-card-accent-orange-bg': '#431407',
        'dark-card-accent-orange-text': '#FDBA74',
        background: '#18181B',
        surface: '#27272A',
        'text-primary': '#FAFAFA',
        'text-secondary': '#A1A1AA',
        'light-background': '#F8FAFC',
        'light-surface': '#FFFFFF',
        'light-text-primary': '#1E293B',
        'light-text-secondary': '#64748B',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}