import React, { useState, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';
import Card from '../components/ui/Card';
import Modal from '../components/ui/Modal';
import PageHeader from '../components/ui/PageHeader';
import { 
  AVAILABLE_CATEGORY_ICONS, 
  AVAILABLE_CATEGORY_COLORS, 
  getCategoryIcon, 
  DEFAULT_TRANSACTION_CATEGORIES 
} from '../utils/categoryIcons';
import { TransactionCategory } from '../types';
import { 
  HiOutlineTag, 
  HiPlus, 
  HiPencil, 
  HiTrash, 
  HiOutlineExclamationTriangle,
  HiOutlineArrowPath,
  HiCheck,
  HiOutlineFunnel,
  HiOutlineMagnifyingGlass,
  HiOutlineSparkles,
  HiOutlineReceiptPercent,
  HiOutlineDocumentText
} from 'react-icons/hi2';
import toast from 'react-hot-toast';
import { useTranslation } from '../hooks/useTranslation';

export const CategoriesSettingsPage: React.FC = () => {
  const { 
    transactionCategories, 
    addTransactionCategory, 
    updateTransactionCategory, 
    deleteTransactionCategory,
    mergeTransactionCategories,
    transactions,
    bills,
    currency,
    availableCurrencies,
  } = useAppContext();

  const navigate = useNavigate();
  const { t } = useTranslation();

  // Search & Filter state
  const [searchQuery, setSearchQuery] = useState('');
  const [filterType, setFilterType] = useState<'all' | 'custom' | 'default' | 'anomalies'>('all');

  // Modal states
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [editingCategory, setEditingCategory] = useState<TransactionCategory | null>(null);
  const [deletingCategory, setDeletingCategory] = useState<TransactionCategory | null>(null);
  const [isCleanupModalOpen, setIsCleanupModalOpen] = useState(false);

  // Form state
  const [formName, setFormName] = useState('');
  const [formIcon, setFormIcon] = useState(AVAILABLE_CATEGORY_ICONS[0].name);
  const [formColor, setFormColor] = useState(AVAILABLE_CATEGORY_COLORS[0]);

  // Currency symbol
  const currencySymbol = useMemo(() => 
    availableCurrencies.find(c => c.code === currency)?.symbol || '$',
    [currency, availableCurrencies]
  );

  // Helper to detect auto-generated "Cat-xxxx" category names
  const isAutoGeneratedName = (name: string) => {
    return /^cat-[a-f0-9]{6,12}$/i.test(name.trim());
  };

  // Detect all auto-generated anomaly categories
  const anomalyCategories = useMemo(() => {
    return transactionCategories.filter(c => isAutoGeneratedName(c.name));
  }, [transactionCategories]);

  // Compute usage statistics for each category
  const usageStats = useMemo(() => {
    const stats: Record<string, { txCount: number; billCount: number; totalAmount: number }> = {};
    transactionCategories.forEach(cat => {
      stats[cat.id] = { txCount: 0, billCount: 0, totalAmount: 0 };
    });

    transactions.forEach(tx => {
      if (tx.categoryId && stats[tx.categoryId]) {
        stats[tx.categoryId].txCount += 1;
        stats[tx.categoryId].totalAmount += Math.abs(tx.amount || 0);
      }
    });

    bills.forEach(bill => {
      if (bill.categoryId && stats[bill.categoryId]) {
        stats[bill.categoryId].billCount += 1;
      }
    });

    return stats;
  }, [transactionCategories, transactions, bills]);

  // Filtered categories
  const filteredCategories = useMemo(() => {
    return transactionCategories.filter(cat => {
      const matchesSearch = cat.name.toLowerCase().includes(searchQuery.toLowerCase());
      if (!matchesSearch) return false;

      if (filterType === 'custom') return cat.isCustom;
      if (filterType === 'default') return !cat.isCustom;
      if (filterType === 'anomalies') return isAutoGeneratedName(cat.name);
      return true;
    });
  }, [transactionCategories, searchQuery, filterType]);

  // Open Edit Modal
  const handleOpenEdit = (category: TransactionCategory) => {
    setEditingCategory(category);
    setFormName(category.name);
    setFormIcon(category.icon || 'HiOutlineTag');
    setFormColor(category.color || '#6366F1');
  };

  // Open Add Modal
  const handleOpenAdd = () => {
    setEditingCategory(null);
    setFormName('');
    setFormIcon(AVAILABLE_CATEGORY_ICONS[0].name);
    setFormColor(AVAILABLE_CATEGORY_COLORS[0]);
    setIsAddModalOpen(true);
  };

  // Save Category (Add or Update)
  const handleSaveCategory = (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = formName.trim();
    if (!trimmed) {
      toast.error('Please enter a category name');
      return;
    }

    // Check duplicates
    const duplicate = transactionCategories.find(c => 
      c.name.toLowerCase() === trimmed.toLowerCase() && (!editingCategory || c.id !== editingCategory.id)
    );

    if (editingCategory) {
      // If user renamed an existing category to match another existing category, merge them cleanly!
      if (duplicate) {
        mergeTransactionCategories(editingCategory.id, duplicate.id);
        toast.success(`Merged "${editingCategory.name}" into existing "${duplicate.name}" category!`);
        setEditingCategory(null);
        return;
      }

      updateTransactionCategory({
        ...editingCategory,
        name: trimmed,
        icon: formIcon,
        color: formColor,
      });
      toast.success(`Category "${trimmed}" updated!`);
      setEditingCategory(null);
    } else {
      if (duplicate) {
        toast.error(`A category named "${trimmed}" already exists`);
        return;
      }

      addTransactionCategory({
        name: trimmed,
        icon: formIcon,
        color: formColor,
        isCustom: true,
      });
      toast.success(`Category "${trimmed}" added!`);
      setIsAddModalOpen(false);
    }
  };

  // Confirm Delete
  const handleConfirmDelete = () => {
    if (!deletingCategory) return;
    deleteTransactionCategory(deletingCategory.id);
    toast.success(`Category "${deletingCategory.name}" removed and items reassigned to Other`);
    setDeletingCategory(null);
  };

  // Batch Clean Up Auto-Generated Categories
  const handleBatchCleanup = () => {
    if (anomalyCategories.length === 0) return;
    const count = anomalyCategories.length;
    anomalyCategories.forEach(cat => {
      deleteTransactionCategory(cat.id);
    });
    setIsCleanupModalOpen(false);
    toast.success(`Cleaned up ${count} auto-generated categories and merged their records into "Other"!`);
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-light-text-primary dark:text-text-primary">
            Manage Categories
          </h1>
          <p className="text-xs sm:text-sm text-light-text-secondary dark:text-text-secondary mt-0.5">
            Customize, rename, and organize categories for transactions and household bills
          </p>
        </div>

        <button
          onClick={handleOpenAdd}
          className="inline-flex items-center justify-center gap-2 px-4 py-2.5 bg-primary text-white text-sm font-semibold rounded-xl hover:bg-opacity-95 active:scale-[0.98] shadow-sm transition-all self-start sm:self-auto"
        >
          <HiPlus className="w-4 h-4" />
          New Category
        </button>
      </div>

      {/* Auto-Generated Anomaly Banner */}
      {anomalyCategories.length > 0 && (
        <div className="p-4 sm:p-5 rounded-2xl bg-amber-500/10 border border-amber-500/30 text-amber-900 dark:text-amber-200">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-start gap-3">
              <div className="p-2 rounded-xl bg-amber-500/20 text-amber-600 dark:text-amber-400 shrink-0 mt-0.5 sm:mt-0">
                <HiOutlineExclamationTriangle className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-amber-800 dark:text-amber-300">
                  {anomalyCategories.length} Auto-Generated {anomalyCategories.length === 1 ? 'Category' : 'Categories'} Detected
                </h3>
                <p className="text-xs text-amber-700 dark:text-amber-400/90 mt-0.5 max-w-2xl">
                  These categories (like <code className="px-1 py-0.5 rounded bg-amber-500/20 font-mono text-[11px] font-bold">{anomalyCategories[0]?.name}</code>) were automatically generated during earlier transaction syncs. You can rename them to real labels (e.g. "Dining", "Groceries") using the edit pencil below, or click clean up to merge them into "Other".
                </p>
              </div>
            </div>

            <button
              onClick={() => setIsCleanupModalOpen(true)}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 bg-amber-600 dark:bg-amber-500 text-white text-xs font-semibold rounded-xl hover:bg-amber-700 active:scale-95 transition-all shadow-xs shrink-0 self-start sm:self-center"
            >
              <HiOutlineArrowPath className="w-4 h-4" />
              Clean Up & Merge to Other
            </button>
          </div>
        </div>
      )}

      {/* Overview Stats Bar */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <Card className="p-3.5 sm:p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-light-text-secondary dark:text-text-secondary">
            Total Categories
          </p>
          <p className="text-xl sm:text-2xl font-bold text-light-text-primary dark:text-text-primary mt-1">
            {transactionCategories.length}
          </p>
        </Card>

        <Card className="p-3.5 sm:p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-light-text-secondary dark:text-text-secondary">
            Custom
          </p>
          <p className="text-xl sm:text-2xl font-bold text-primary mt-1">
            {transactionCategories.filter(c => c.isCustom).length}
          </p>
        </Card>

        <Card className="p-3.5 sm:p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-light-text-secondary dark:text-text-secondary">
            Active in Transactions
          </p>
          <p className="text-xl sm:text-2xl font-bold text-emerald-600 dark:text-emerald-400 mt-1">
            {transactions.length}
          </p>
        </Card>

        <Card className="p-3.5 sm:p-4">
          <p className="text-[11px] font-semibold uppercase tracking-wider text-light-text-secondary dark:text-text-secondary">
            Active in Bills
          </p>
          <p className="text-xl sm:text-2xl font-bold text-indigo-600 dark:text-indigo-400 mt-1">
            {bills.length}
          </p>
        </Card>
      </div>

      {/* Search & Filter Toolbar */}
      <div className="flex flex-col sm:flex-row gap-3 items-stretch sm:items-center justify-between">
        <div className="relative flex-1 max-w-md">
          <HiOutlineMagnifyingGlass className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 dark:text-zinc-500" />
          <input
            type="text"
            placeholder="Search categories by name..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-4 py-2 text-xs sm:text-sm rounded-xl border border-slate-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-light-text-primary dark:text-text-primary placeholder-slate-400 dark:placeholder-zinc-500 focus:outline-none focus:ring-2 focus:ring-primary/40"
          />
        </div>

        <div className="flex items-center gap-1.5 overflow-x-auto pb-1 sm:pb-0">
          <button
            onClick={() => setFilterType('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
              filterType === 'all'
                ? 'bg-primary text-white'
                : 'bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 hover:bg-slate-200 dark:hover:bg-zinc-700'
            }`}
          >
            All ({transactionCategories.length})
          </button>
          <button
            onClick={() => setFilterType('custom')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
              filterType === 'custom'
                ? 'bg-primary text-white'
                : 'bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 hover:bg-slate-200 dark:hover:bg-zinc-700'
            }`}
          >
            Custom ({transactionCategories.filter(c => c.isCustom).length})
          </button>
          <button
            onClick={() => setFilterType('default')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
              filterType === 'default'
                ? 'bg-primary text-white'
                : 'bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 hover:bg-slate-200 dark:hover:bg-zinc-700'
            }`}
          >
            System Default
          </button>
          {anomalyCategories.length > 0 && (
            <button
              onClick={() => setFilterType('anomalies')}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors flex items-center gap-1 ${
                filterType === 'anomalies'
                  ? 'bg-amber-600 text-white'
                  : 'bg-amber-500/10 text-amber-700 dark:text-amber-400 hover:bg-amber-500/20'
              }`}
            >
              <span>Auto-Generated</span>
              <span className="w-4 h-4 rounded-full bg-amber-500 text-white text-[10px] flex items-center justify-center font-bold">
                {anomalyCategories.length}
              </span>
            </button>
          )}
        </div>
      </div>

      {/* Category Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
        {filteredCategories.map(cat => {
          const Icon = getCategoryIcon(cat.icon);
          const stats = usageStats[cat.id] || { txCount: 0, billCount: 0, totalAmount: 0 };
          const isAnomaly = isAutoGeneratedName(cat.name);

          return (
            <div 
              key={cat.id}
              onClick={() => handleOpenEdit(cat)}
              className={`p-4 rounded-2xl bg-white dark:bg-zinc-800/90 border transition-all flex flex-col justify-between gap-3 shadow-xs cursor-pointer hover:shadow-md hover:border-primary/50 ${
                isAnomaly 
                  ? 'border-amber-500/40 dark:border-amber-500/30 bg-amber-500/5' 
                  : 'border-slate-200/80 dark:border-zinc-700/80'
              }`}
              title={`Click to edit ${cat.name}`}
            >
              <div className="flex items-start justify-between gap-2">
                <div className="flex items-center gap-3 min-w-0">
                  <div 
                    className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0 shadow-xs"
                    style={{ backgroundColor: `${cat.color}20`, color: cat.color }}
                  >
                    <Icon className="w-5 h-5" />
                  </div>
                  <div className="min-w-0">
                    <div className="flex items-center gap-1.5">
                      <h4 className="font-bold text-sm text-light-text-primary dark:text-text-primary truncate">
                        {cat.name}
                      </h4>
                      {isAnomaly ? (
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-amber-500/20 text-amber-700 dark:text-amber-300">
                          Needs Rename
                        </span>
                      ) : cat.isCustom ? (
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-primary/10 text-primary">
                          Custom
                        </span>
                      ) : (
                        <span className="px-1.5 py-0.5 rounded text-[10px] font-medium bg-slate-100 dark:bg-zinc-700 text-slate-500 dark:text-zinc-400">
                          Default
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-1 shrink-0" onClick={(e) => e.stopPropagation()}>
                  <button
                    onClick={() => handleOpenEdit(cat)}
                    className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 dark:bg-zinc-700 dark:hover:bg-zinc-600 text-light-text-primary dark:text-text-primary hover:text-primary transition-colors text-xs font-semibold"
                    title="Edit Category Name, Icon & Color"
                    aria-label={`Edit ${cat.name}`}
                  >
                    <HiPencil className="w-3.5 h-3.5" />
                    <span>Edit</span>
                  </button>

                  <button
                    onClick={() => setDeletingCategory(cat)}
                    className="p-1.5 rounded-lg hover:bg-red-50 dark:hover:bg-red-950/30 text-light-text-secondary dark:text-text-secondary hover:text-red-500 transition-colors"
                    title="Delete Category"
                    aria-label={`Delete ${cat.name}`}
                  >
                    <HiTrash className="w-4 h-4" />
                  </button>
                </div>
              </div>

              {/* Usage Metrics */}
              <div className="pt-2 border-t border-slate-100 dark:border-zinc-700/60 flex items-center justify-between text-xs text-light-text-secondary dark:text-text-secondary">
                <span className="inline-flex items-center gap-1">
                  <HiOutlineReceiptPercent className="w-3.5 h-3.5 opacity-70" />
                  <span>{stats.txCount} {stats.txCount === 1 ? 'tx' : 'txs'}</span>
                </span>

                <span className="inline-flex items-center gap-1">
                  <HiOutlineDocumentText className="w-3.5 h-3.5 opacity-70" />
                  <span>{stats.billCount} {stats.billCount === 1 ? 'bill' : 'bills'}</span>
                </span>

                <span className="font-semibold text-light-text-primary dark:text-text-primary">
                  {currencySymbol}{stats.totalAmount.toFixed(0)}
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {filteredCategories.length === 0 && (
        <div className="py-12 text-center">
          <div className="w-12 h-12 rounded-full bg-slate-100 dark:bg-zinc-800 text-slate-400 flex items-center justify-center mx-auto mb-3">
            <HiOutlineTag className="w-6 h-6" />
          </div>
          <h3 className="font-bold text-sm text-light-text-primary dark:text-text-primary">
            No categories found
          </h3>
          <p className="text-xs text-light-text-secondary dark:text-text-secondary mt-1">
            Try adjusting your search query or filter selection
          </p>
        </div>
      )}

      {/* Edit / Add Modal */}
      <Modal
        isOpen={isAddModalOpen || editingCategory !== null}
        onClose={() => {
          setIsAddModalOpen(false);
          setEditingCategory(null);
        }}
        title={editingCategory ? `Edit Category: ${editingCategory.name}` : 'Create New Category'}
      >
        <form onSubmit={handleSaveCategory} className="space-y-4 pt-1">
          {/* Live Preview */}
          <div className="p-3.5 rounded-xl bg-slate-50 dark:bg-zinc-800/80 border border-slate-200 dark:border-zinc-700/80 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div 
                className="w-10 h-10 rounded-xl flex items-center justify-center shadow-xs"
                style={{ backgroundColor: `${formColor}20`, color: formColor }}
              >
                {(() => {
                  const PreviewIcon = getCategoryIcon(formIcon);
                  return <PreviewIcon className="w-5 h-5" />;
                })()}
              </div>
              <div>
                <p className="text-xs text-light-text-secondary dark:text-text-secondary">Preview</p>
                <p className="font-bold text-sm text-light-text-primary dark:text-text-primary">
                  {formName.trim() || 'Category Name'}
                </p>
              </div>
            </div>
            <div 
              className="px-2 py-0.5 rounded-full text-[11px] font-semibold"
              style={{ backgroundColor: `${formColor}20`, color: formColor }}
            >
              Active
            </div>
          </div>

          {/* Name Input */}
          <div className="space-y-1.5">
            <label className="block text-xs font-semibold text-light-text-secondary dark:text-text-secondary uppercase tracking-wider">
              Category Name *
            </label>
            <input
              type="text"
              required
              placeholder="e.g. Dining Out, Gym, Pet Care, Freelance..."
              value={formName}
              onChange={(e) => setFormName(e.target.value)}
              className="w-full px-3.5 py-2.5 text-sm rounded-xl border border-slate-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-light-text-primary dark:text-text-primary focus:outline-none focus:ring-2 focus:ring-primary/40"
            />
            {editingCategory && isAutoGeneratedName(editingCategory.name) && (
              <p className="text-[11px] text-amber-600 dark:text-amber-400">
                💡 Tip: Renaming this category will update all existing transactions that had this ID!
              </p>
            )}
          </div>

          {/* Color Picker */}
          <div className="space-y-1.5">
            <label className="block text-xs font-semibold text-light-text-secondary dark:text-text-secondary uppercase tracking-wider">
              Color Accent
            </label>
            <div className="flex flex-wrap gap-2 pt-1">
              {AVAILABLE_CATEGORY_COLORS.map(c => {
                const isSelected = formColor.toLowerCase() === c.toLowerCase();
                return (
                  <button
                    key={c}
                    type="button"
                    onClick={() => setFormColor(c)}
                    className={`w-7 h-7 rounded-full transition-transform flex items-center justify-center ${
                      isSelected ? 'scale-110 ring-2 ring-offset-2 ring-primary' : 'hover:scale-105'
                    }`}
                    style={{ backgroundColor: c }}
                  >
                    {isSelected && <HiCheck className="w-4 h-4 text-white drop-shadow-xs" />}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Icon Picker */}
          <div className="space-y-1.5">
            <label className="block text-xs font-semibold text-light-text-secondary dark:text-text-secondary uppercase tracking-wider">
              Icon
            </label>
            <div className="grid grid-cols-6 sm:grid-cols-8 gap-2 max-h-48 overflow-y-auto p-1.5 border border-slate-200 dark:border-zinc-700 rounded-xl bg-slate-50/50 dark:bg-zinc-900/30">
              {AVAILABLE_CATEGORY_ICONS.map(item => {
                const IconComponent = item.icon;
                const isSelected = formIcon === item.name;
                return (
                  <button
                    key={item.name}
                    type="button"
                    onClick={() => setFormIcon(item.name)}
                    title={item.label}
                    className={`p-2 rounded-xl flex items-center justify-center transition-all ${
                      isSelected
                        ? 'bg-primary text-white shadow-xs scale-105'
                        : 'bg-white dark:bg-zinc-800 text-slate-600 dark:text-zinc-300 hover:bg-slate-100 dark:hover:bg-zinc-700 border border-slate-200 dark:border-zinc-700'
                    }`}
                  >
                    <IconComponent className="w-5 h-5" />
                  </button>
                );
              })}
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex justify-end gap-2.5 pt-2">
            <button
              type="button"
              onClick={() => {
                setIsAddModalOpen(false);
                setEditingCategory(null);
              }}
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-slate-100 dark:bg-zinc-700 text-slate-700 dark:text-zinc-300 hover:bg-slate-200 dark:hover:bg-zinc-600 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-primary text-white hover:bg-opacity-90 transition-colors shadow-xs"
            >
              {editingCategory ? 'Save Changes' : 'Create Category'}
            </button>
          </div>
        </form>
      </Modal>

      {/* Delete Confirmation Modal */}
      <Modal
        isOpen={deletingCategory !== null}
        onClose={() => setDeletingCategory(null)}
        title={`Delete Category: ${deletingCategory?.name}`}
      >
        <div className="space-y-4 pt-1">
          <p className="text-sm text-light-text-secondary dark:text-text-secondary">
            Are you sure you want to delete <strong className="text-light-text-primary dark:text-text-primary font-bold">"{deletingCategory?.name}"</strong>?
          </p>

          {deletingCategory && usageStats[deletingCategory.id] && (usageStats[deletingCategory.id].txCount > 0 || usageStats[deletingCategory.id].billCount > 0) && (
            <div className="p-3 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-800 dark:text-amber-300 text-xs">
              ⚠️ This category is currently used by <strong>{usageStats[deletingCategory.id].txCount} transaction(s)</strong> and <strong>{usageStats[deletingCategory.id].billCount} bill(s)</strong>.
              <br />
              Deleting it will safely reassign those records to the <strong>"Other"</strong> category.
            </div>
          )}

          <div className="flex justify-end gap-2.5 pt-2">
            <button
              onClick={() => setDeletingCategory(null)}
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-slate-100 dark:bg-zinc-700 text-slate-700 dark:text-zinc-300 hover:bg-slate-200 dark:hover:bg-zinc-600 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleConfirmDelete}
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-red-600 text-white hover:bg-red-700 transition-colors shadow-xs"
            >
              Yes, Delete & Reassign
            </button>
          </div>
        </div>
      </Modal>

      {/* Batch Cleanup Modal */}
      <Modal
        isOpen={isCleanupModalOpen}
        onClose={() => setIsCleanupModalOpen(false)}
        title="Clean Up Auto-Generated Categories"
      >
        <div className="space-y-4 pt-1">
          <p className="text-sm text-light-text-secondary dark:text-text-secondary">
            This will permanently remove <strong className="text-light-text-primary dark:text-text-primary font-bold">{anomalyCategories.length} auto-generated categories</strong> (e.g. {anomalyCategories.slice(0, 3).map(c => c.name).join(', ')}) and safely merge any associated transactions or bills into the default <strong className="text-primary font-semibold">"Other"</strong> category.
          </p>
          <div className="p-3 rounded-xl bg-slate-100 dark:bg-zinc-800 text-xs text-light-text-secondary dark:text-text-secondary">
            💡 If any of these categories represent real transactions you wish to keep categorized, you can simply click <strong>Edit</strong> on them instead of batch cleaning!
          </div>

          <div className="flex justify-end gap-2.5 pt-2">
            <button
              onClick={() => setIsCleanupModalOpen(false)}
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-slate-100 dark:bg-zinc-700 text-slate-700 dark:text-zinc-300 hover:bg-slate-200 dark:hover:bg-zinc-600 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleBatchCleanup}
              className="px-4 py-2 text-xs sm:text-sm font-semibold rounded-xl bg-amber-600 text-white hover:bg-amber-700 transition-colors shadow-xs"
            >
              Merge All into Other
            </button>
          </div>
        </div>
      </Modal>
    </div>
  );
};
